/**
 * Copies the Next.js static export (out/) into the host Frappe app:
 *
 *   out/_next, images, fonts, ...  →  ../__APP__/public/__SPA__/   (served at /assets/__APP__/__SPA__/)
 *   out/index.html                 →  ../__APP__/www/__SPA__.html  (served at /__SPA__)
 *   out/<page>.html                →  ../__APP__/www/__SPA__/<page>.html (served at /__SPA__/<page>)
 *
 * A CSRF bootstrap script is injected into every HTML entry. Frappe
 * renders www/*.html through Jinja, so `{{ frappe.session.csrf_token }}`
 * resolves at request time.
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

const APP = "__APP__";
const SPA = "__SPA__";
const OUT = "out";

const publicDir = path.join("..", APP, "public", SPA);
const wwwDir = path.join("..", APP, "www", SPA);
const wwwEntry = path.join("..", APP, "www", `${SPA}.html`);

const CSRF_SNIPPET =
  "<script>window.csrf_token = '{{ frappe.session.csrf_token }}';</script>";

// Next.js HTML contains `.__` sequences (e.g. self.__next_f) that trip
// Frappe v15's Jinja safe_render guard ("Illegal template"). A sidecar
// .py sets context.safe_render = False — the CSRF token still renders.
const SIDECAR_PY = `# Auto-generated by copy-export.mjs — do not edit.
# Next.js HTML contains \`.__\` sequences that trip Frappe v15's Jinja
# safe_render guard. Rendering stays enabled for the CSRF snippet.
def get_context(context):
    context.safe_render = False
`;

// Frappe imports the sidecar as <app>.www...<name> — hyphens become
// underscores and every directory on the way needs an __init__.py.
function sidecarPath(htmlPath) {
  const base = path.basename(htmlPath, ".html").replace(/-/g, "_");
  return path.join(path.dirname(htmlPath), `${base}.py`);
}

const wwwRoot = path.join("..", APP, "www");
const initialized = new Set();
function ensurePackage(dir) {
  let current = dir;
  while (current.startsWith(wwwRoot)) {
    if (!initialized.has(current)) {
      // The __init__.py carries get_context too: for pages that have a
      // same-named directory (frontend.html + frontend/, blog.html +
      // blog/), Python resolves the controller import to the PACKAGE,
      // shadowing the sidecar .py — so the package must provide it.
      writeFileSync(path.join(current, "__init__.py"), SIDECAR_PY);
      initialized.add(current);
    }
    if (current === wwwRoot) break;
    current = path.dirname(current);
  }
}

function writeHtmlWithSidecar(dest, html) {
  writeFileSync(dest, html);
  writeFileSync(sidecarPath(dest), SIDECAR_PY);
  ensurePackage(path.dirname(dest));
}

if (!existsSync(OUT)) {
  console.error(`"${OUT}" not found — run \`next build\` first.`);
  process.exit(1);
}

// Clean previous build output
for (const target of [publicDir, wwwDir, wwwEntry]) {
  rmSync(target, { recursive: true, force: true });
}
rmSync(
  path.join(
    path.dirname(wwwEntry),
    `${path.basename(wwwEntry, ".html").replace(/-/g, "_")}.py`
  ),
  { force: true }
);
mkdirSync(publicDir, { recursive: true });
mkdirSync(wwwDir, { recursive: true });

function injectCsrf(html) {
  if (html.includes("</head>")) {
    return html.replace("</head>", `${CSRF_SNIPPET}</head>`);
  }
  return CSRF_SNIPPET + html;
}

function walk(dir) {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    const rel = path.relative(OUT, full);

    if (statSync(full).isDirectory()) {
      walk(full);
      continue;
    }

    if (full.endsWith(".html")) {
      const html = injectCsrf(readFileSync(full, "utf8"));

      if (rel === "index.html") {
        writeHtmlWithSidecar(wwwEntry, html);
      } else {
        const dest = path.join(wwwDir, rel);
        mkdirSync(path.dirname(dest), { recursive: true });
        writeHtmlWithSidecar(dest, html);
      }
    } else {
      // Static asset → app public dir (includes _next/, .txt RSC payloads, etc.)
      const dest = path.join(publicDir, rel);
      mkdirSync(path.dirname(dest), { recursive: true });
      cpSync(full, dest);
    }
  }
}

walk(OUT);

console.log(`✓ assets  → ${publicDir}`);
console.log(`✓ entry   → ${wwwEntry}`);
console.log(`✓ pages   → ${wwwDir}`);
console.log(`\nRun \`bench build --app ${APP}\` / restart bench, then open /${SPA}`);
